# KHAI BÁO THƯ VIỆN

In [6]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
from numpy.linalg import norm
from numpy.linalg import matrix_rank
from sklearn import datasets,linear_model

BỘ DỮ LIỆU DÙNG ĐỂ DỰ ĐOÁN GIÁ NHÀ

In [7]:
DATA=pd.read_csv("archive (1)/kc_house_data.csv")
DATA

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,263000018,20140521T000000,360000.0,3,2.50,1530,1131,3.0,0,0,...,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
21609,6600060120,20150223T000000,400000.0,4,2.50,2310,5813,2.0,0,0,...,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
21610,1523300141,20140623T000000,402101.0,2,0.75,1020,1350,2.0,0,0,...,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
21611,291310100,20150116T000000,400000.0,3,2.50,1600,2388,2.0,0,0,...,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
21612,1523300157,20141015T000000,325000.0,2,0.75,1020,1076,2.0,0,0,...,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357

PHƯƠNG PHÁP ĐẠO HÀM, TÌM ĐIỂM CỰC TIỂU, DÙNG ĐẾN GIẢ NGHỊCH ĐẢO

In [8]:
X = np.array(DATA[['sqft_living','sqft_lot','sqft_above','sqft_basement','sqft_living15','sqft_lot15','bathrooms']])
one=np.ones((X.shape[0],1))
Xbar=np.concatenate((one,X),axis=1)
Y= np.array(DATA['price'])

TÌM ĐIỂM CỰC TIỂU

In [9]:
A=np.dot(Xbar.T,Xbar)
b=np.dot(Xbar.T,Y)
w=np.dot(np.linalg.pinv(A),b)

TÍNH L2 NORM CỦA LOSS FUNCTION KHI CHƯA CHIA CHO SỐ ĐIỂM DỮ LIỆU

In [10]:
norm(np.dot(Xbar,w)-Y)

38010768.97675811

NGHIỆM

In [11]:
print(w)

[-9.60690426e+04  1.69290211e+02  7.96850138e-02  6.75505920e+01
  1.01746126e+02  7.77796884e+01 -7.91736244e-01 -5.68586789e+03]

Kiểm tra tính singular

In [12]:
print(matrix_rank(A))

7

PHƯƠNG PHÁP DÙNG THƯ VIỆN linear_model.LinearRegression()

In [13]:
regr=linear_model.LinearRegression()
regr.fit(X,Y)
print(regr.intercept_)

-96069.0425613086

TÌM L2 NORM CHO LOSS FUNCTION KHI CHƯA CHIA CHO SỐ ĐIỂM DỮ LIỆU

In [14]:
print(norm(regr.predict(X)-Y))

38010768.97675811

NGHIỆM

In [15]:
print(regr.intercept_)
print(regr.coef_)

-96069.0425613086
[ 1.69292380e+02  7.96850138e-02  6.75484231e+01  1.01743957e+02
  7.77796884e+01 -7.91736244e-01 -5.68586790e+03]

Nếu ta bỏ cột 'long' trong X đi thì A nghịch đảo được. Do đó kết quả lại giống nhau.

In [16]:
X = np.array(DATA[['sqft_living','sqft_lot','sqft_above','sqft_basement','sqft_living15','sqft_lot15','bathrooms']])
one=np.ones((X.shape[0],1))
Xbar=np.concatenate((one,X),axis=1)
Y= np.array(DATA['price'])

In [17]:
A=np.dot(Xbar.T,Xbar)
b=np.dot(Xbar.T,Y)
w=np.dot(np.linalg.pinv(A),b)

In [18]:
norm(np.dot(Xbar,w)-Y)

38010768.97675811

In [19]:
print(w)

[-9.60690426e+04  1.69290211e+02  7.96850138e-02  6.75505920e+01
  1.01746126e+02  7.77796884e+01 -7.91736244e-01 -5.68586789e+03]

Kiểm tra tính singular

In [20]:
print(matrix_rank(A))

7

In [21]:
from sklearn import datasets,linear_model
regr=linear_model.LinearRegression()
regr.fit(X,Y)
print(regr.intercept_)

-96069.0425613086

In [22]:
print(norm(regr.predict(X)-Y))

38010768.97675811

In [23]:
print(regr.intercept_)
print(regr.coef_)

-96069.0425613086
[ 1.69292380e+02  7.96850138e-02  6.75484231e+01  1.01743957e+02
  7.77796884e+01 -7.91736244e-01 -5.68586790e+03]